drop table contacto if exists;

create table contacto 
(id bigint generated by default as identity, 
 nombre varchar(100),
 nacimiento date,
 email varchar(120),
 telefono varchar(20),
 direccion varchar(255),
 localidad bigint,
 primary key (id)) ; 

insert into contacto 
values 
(213, 'Rogelio Salmona', '1967-12-06', 'rsalmon@email.com',  null, 'Av.San Matin 2321 1C', 11809),
(219, 'Marina Waisman', '1940-04-29', 'waisman@email.com',  null, null, 11809),
(222, 'Antonio Ochoa', '1943-09-18', 'ochoaaa@hotmail.com',  '021-41202243', 'Callao 32', 12202),
(354, 'Cesar Pelli', '1987-05-01', 'pellic@gmail.com',  '030-45544332', 'Viamonte 3211 3A', 12202),
(355, 'Ruth Rivera', '1987-12-09', 'rivera@gmail.com',  '055-5554430', 'Mexico 802', 13013),
(361, 'Rafael Viñoly', '1963-10-12', 'virafa@email.com',  '0121-1344452', 'Caracas 1237', 12202),
(362, 'Carmen Córdova', '1990-09-18', 'china@email.com',  null, null, 12202),
(363, 'Glenda Kapstein', '1979-04-29', 'kapstein@gmail.com',  '4211211', 'Av.9 de Julio 211', 13503),
(364, 'Tatiana Bilbao', '1992-07-07', 'bilbaota@hotmail.com',  null, 'Chaco y Pres.Peña', 14003);
